relearn/urls.py
from django.conf.urls import patterns, include, url
from django.views.generic import TemplateView
from django.http import HttpResponse

from django.conf import settings
from django.conf.urls.static import static

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

# This is to allow the website to work under a subfolder
# i.e. http://relearn.be/2015/
# Define SUBFOLDER in your local_settings.py
BASE_URL = '^'
try:
    BASE_URL = r'^' + settings.SUBFOLDER
    if BASE_URL and not BASE_URL.endswith(r'/'):
        BASE_URL += r'/'
except AttributeError:
    pass

base_urlpatterns = patterns(
    '',
    url(r'^admin/', include(admin.site.urls)),
    url(r'^all/$', TemplateView.as_view(template_name = 'all.html'), name='all'),
    url(r'^css/$', 'relearn.views.css', name='css'),
    url(r'^publish/$', 'relearn.views.publish', name='publish'),
    url(r'^css-print/$', 'relearn.views.cssprint', name='css-print'),
    url(r'^offset-print/$', 'relearn.views.offsetprint', name='offset-print'),
    url(r'^css-slide/$', 'relearn.views.css_slide', name='css-slide'),
    url(r'^$', 'relearn.views.home', name='home'),
    url(r'^(?P<slug>[^/]+)\.xhtml$', 'relearn.views.xhtml', name='xhtml'),
    url(r'^accounts/login$', 'django.contrib.auth.views.login',
        {'template_name': 'login.html'}, name='login'),
    url(r'^accounts/logout$', 'django.contrib.auth.views.logout',
        {'template_name': 'logout.html'}, name='logout'),
    url(r'^create/$', 'relearn.views.padCreate', name='pad-create'),
    url(r'(?P<mode>[r|s|p])/(?P<slug>[^/]+)$', 'relearn.views.pad_read', name='pad-read'),
    #url(r'r/(?P<slug>[^/]+)$', 'relearn.views.pad', name='pad-read'),
    #url(r's/(?P<slug>[^/]+)$', 'relearn.views.pad', name='pad-slide'),
    #url(r'p/(?P<slug>[^/]+)$', 'relearn.views.pad', name='pad-print'),
    url(r'w/(?P<slug>[^/]+)$', 'relearn.views.pad', name='pad-write'),
) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns = patterns('',
    url(BASE_URL , include(base_urlpatterns)),
)

relearn/forms.py
from django import forms
from django.utils.translation import ugettext_lazy as _


class ContactForm(forms.Form):
    name         = forms.CharField(max_length=50, label=_("First Name"))
    email        = forms.EmailField(label=_("E-Mail"))
    subject      = forms.CharField(max_length=100, label=_("Subject"))
    message      = forms.CharField(widget=forms.Textarea(), label=_("Message"))

relearn/views.py
# -*- coding: utf-8 -*-

# Python imports
import datetime
import time
import urllib
from urlparse import urlparse
import HTMLParser
import json
import re
import os

# PyPi imports

import markdown
from py_etherpad import EtherpadLiteClient
import dateutil.parser
import pytz

# Framework imports
from django.shortcuts import render_to_response, get_object_or_404

from django.http import HttpResponse, HttpResponseRedirect
from django.template import RequestContext
from django.template.defaultfilters import slugify
from django.core.urlresolvers import reverse
from django.core.context_processors import csrf
from django.core.exceptions import PermissionDenied
from django.contrib.auth.decorators import login_required
from django.utils.translation import ugettext_lazy as _

# Django Apps import

from etherpadlite.models import *
from etherpadlite import forms
from etherpadlite import config
from django.contrib.sites.models import get_current_site

from relearn.management.commands.index import snif

# By default, the homepage is the pad called ‘start’ (props to DokuWiki!)
try:
    from relearn.settings import HOME_PAD
except ImportError:
    HOME_PAD = 'About.md'
try:
    from relearn.settings import BACKUP_DIR
except ImportError:
    BACKUP_DIR = None

"""
Set up an HTMLParser for the sole purpose of unescaping
Etherpad’s HTML entities.
cf http://fredericiana.com/2010/10/08/decoding-html-entities-to-text-in-python/
"""

h = HTMLParser.HTMLParser()
unescape = h.unescape

"""
Create a regex for our include template tag
"""
include_regex = re.compile("{%\s?include\s?\"([\w._-]+)\"\s?%}")

@login_required(login_url='/accounts/login')
def padCreate(request):
    """
    Create a pad
    """
    
    # normally the ‘pads’ context processor should have made sure that these objects exist:
    author = PadAuthor.objects.get(user=request.user)
    group = author.group.all()[0]
    
    if request.method == 'POST':  # Process the form
        form = forms.PadCreate(request.POST)
        if form.is_valid():
            n = form.cleaned_data['name']
            n = re.sub(r'\s+', u'_', n)
            pad = Pad(
                name=slugify(n)[:42], # This is the slug internally used by etherpad
                display_slug=n, # This is the slug we get to change afterwards
                display_name=n,     # this is just for backwards compatibility
                server=group.server,
                group=group
            )
            pad.save()
            return HttpResponseRedirect(reverse('pad-write', args=(pad.display_slug,) ))
    else:  # No form to process so create a fresh one
        form = forms.PadCreate({'group': group.groupID})

    con = {
        'form': form,
        'pk': group.pk,
        'title': _('Create pad in %(grp)s') % {'grp': group.__unicode__()}
    }
    con.update(csrf(request))
    return render_to_response(
        'pad-create.html',
        con,
        context_instance=RequestContext(request)
    )


@login_required(login_url='/accounts/login')
def pad(request, pk=None, slug=None): # pad_write
    """Create and session and display an embedded pad
    """

    # Initialize some needed values
    if slug:
        pad = get_object_or_404(Pad, display_slug=slug)
    else:
        pad = get_object_or_404(Pad, pk=pk)
    padLink = pad.server.url + 'p/' + pad.group.groupID + '$' + \
        urllib.quote_plus(pad.name)
    server = urlparse(pad.server.url)
    author = PadAuthor.objects.get(user=request.user)

    if author not in pad.group.authors.all():
        response = render_to_response(
            'pad.html',
            {
                'pad': pad,
                'link': padLink,
                'server': server,
                'uname': author.user.__unicode__(),
                'error': _('You are not allowed to view or edit this pad')
            },
            context_instance=RequestContext(request)
        )
        return response

    # Create the session on the etherpad-lite side
    expires = datetime.datetime.utcnow() + datetime.timedelta(
        seconds=config.SESSION_LENGTH
    )
    epclient = EtherpadLiteClient(pad.server.apikey, pad.server.apiurl)

    try:
        result = epclient.createSession(
            pad.group.groupID,
            author.authorID,
            time.mktime(expires.timetuple()).__str__()
        )
    except Exception, e:
        response = render_to_response(
            'pad.html',
            {
                'pad': pad,
                'link': padLink,
                'server': server,
                'uname': author.user.__unicode__(),
                'error': _('etherpad-lite session request returned:') +
                ' "' + e.reason + '"'
            },
            context_instance=RequestContext(request)
        )
        return response

    # Set up the response
    response = render_to_response(
        'pad.html',
        {
            'pad': pad,
            'link': padLink,
            'server': server,
            'uname': author.user.__unicode__(),
            'error': False,
            'mode' : 'write'
        },
        context_instance=RequestContext(request)
    )

    # Delete the existing session first
    if ('padSessionID' in request.COOKIES):
        if 'sessionID' in request.COOKIES.keys():
            try:
                epclient.deleteSession(request.COOKIES['sessionID'])
            except ValueError:
                response.delete_cookie('sessionID', server.hostname)
        response.delete_cookie('padSessionID')

    # Set the new session cookie for both the server and the local site
    response.set_cookie(
        'sessionID',
        value=result['sessionID'],
        expires=expires,
        domain=server.hostname,
        httponly=False
    )
    response.set_cookie(
        'padSessionID',
        value=result['sessionID'],
        expires=expires,
        httponly=False
    )
    return response

def xhtml(request, slug):
    return pad_read(request, "r", slug + '.md')

def pad_read(request, mode="r", slug=None):
    """Read only pad
    """
    
    # FIND OUT WHERE WE ARE,
    # then get previous and next
    try:
        articles = json.load(open(os.path.join(BACKUP_DIR, 'index.json')))
    except IOError:
        articles = []
    
    SITE = get_current_site(request)
    href = "http://%s" % SITE.domain + request.path
    
    prev = None
    next = None
    for i, article in enumerate(articles):
        if article['href'] == href:
            if i != 0:        # The first is the most recent article, there is no newer
                next = articles[i-1]
            if i != len(articles) - 1:
                prev = articles[i+1]

    # Initialize some needed values
    pad = get_object_or_404(Pad, display_slug=slug)

    padID = pad.group.groupID + '$' + urllib.quote_plus(pad.name.replace('::', '_'))
    epclient = EtherpadLiteClient(pad.server.apikey, pad.server.apiurl)

    # Etherpad gives us authorIDs in the form ['a.5hBzfuNdqX6gQhgz', 'a.tLCCEnNVJ5aXkyVI']
    # We link them to the Django users DjangoEtherpadLite created for us
    authorIDs = epclient.listAuthorsOfPad(padID)['authorIDs']
    authors = PadAuthor.objects.filter(authorID__in=authorIDs)

    authorship_authors = []
    for author in authors:
        authorship_authors.append({ 'name'  : author.user.first_name if author.user.first_name else author.user.username,
                                    'class' : 'author' + author.authorID.replace('.','_') })
    authorship_authors_json = json.dumps(authorship_authors, indent=2)

    name, extension = os.path.splitext(slug)

    meta = {}

    if not extension:
        # Etherpad has a quasi-WYSIWYG functionality.
        # Though is not alwasy dependable
        text = epclient.getHtml(padID)['html']
        # Quick and dirty hack to allow HTML in pads
        text = unescape(text)
    else:
        # If a pad is named something.css, something.html, something.md etcetera,
        # we don’t want Etherpads automatically generated HTML, we want plain text.
        text = epclient.getText(padID)['text']
        if extension in ['.md', '.markdown']:
            md = markdown.Markdown(extensions=['extra', 'meta', 'headerid(level=2)', 'attr_list', 'figcaption'])
            text = md.convert(text)
            try:
                meta = md.Meta
            except AttributeError:   # Edge-case: this happens when the pad is completely empty
                meta = None
    
    # Convert the {% include %} tags into a form easily digestible by jquery
    # {% include "example.html" %} -> <a id="include-example.html" class="include" href="/r/include-example.html">include-example.html</a>
    def ret(matchobj):
        return '<a id="include-%s" class="include pad-%s" href="%s">%s</a>' % (slugify(matchobj.group(1)), slugify(matchobj.group(1)), reverse('pad-read', args=("r", matchobj.group(1)) ), matchobj.group(1))
    
    text = include_regex.sub(ret, text)
    
    
    # Create namespaces from the url of the pad
    # 'pedagogy::methodology' -> ['pedagogy', 'methodology']
    namespaces = [p.rstrip('-') for p in pad.display_slug.split('::')]

    meta_list = []

    # One needs to set the ‘Static’ metadata to ‘Public’ for the page to be accessible to outside visitors
    if not meta or not 'status' in meta or not meta['status'][0] or not meta['status'][0].lower() in ['public']:
        if not request.user.is_authenticated():
            pass #raise PermissionDenied
    
    if meta and len(meta.keys()) > 0:
        
        # The human-readable date is parsed so we can sort all the articles
        if 'date' in meta:
            meta['date_iso'] = []
            meta['date_parsed'] = []
            for date in meta['date']:
                date_parsed = dateutil.parser.parse(date)
                # If there is no timezone we assume it is in Brussels:
                if not date_parsed.tzinfo:
                    date_parsed = pytz.timezone('Europe/Brussels').localize(date_parsed) 

relearn/templates/all.html
{% extends "base.html" %}
{% load wikify %}

{% block content %}
    <ul id="pads_list">
        {% for pad in pads %}
            <li><a data-uid="{{ pad.display_slug }}" href="{% url 'pad-write' slug=pad.display_slug %}" class="pad-link">{{ pad.display_slug|dewikify }}</a></li>
        {% endfor %}
    </ul>
{% endblock %}

relearn/templates/base.html
{% load wikify relearn_tags %}<!DOCTYPE HTML>
<html xmlns="http://www.w3.org/1999/xhtml" {% if meta.language %} lang="{{ meta.language.0 }}" {% endif %} moznomarginboxes mozdisallowselectionprint>
<head>
    <meta http-equiv="content-type" content="text/html; charset=utf-8">

    <link rel="stylesheet" href="{{ STATIC_URL }}css/reset.css" type="text/css" media="all">
    <link rel="stylesheet" href="{{ STATIC_URL }}css/fonts.css" type="text/css" media="all">
    
    {% block extra_styles %}
        <link rel="stylesheet/less" href="{% url 'css' %}" type="text/css" media="screen">
        <link rel="stylesheet/less" href="{% url 'css-print' %}" type="text/css" media="print">
    {% endblock %}


    <script src="{{ STATIC_URL }}js/less-1.4.1.js" type="text/javascript"> </script>
    <script src="{{ STATIC_URL }}js/jquery-1.11.1.min.js" type="text/javascript"> </script>
    <script src="{{ STATIC_URL }}js/underscore.js" type="text/javascript"> </script>

    {% block head_meta %}{% endblock %}

    <title>{{ site_name }}{% if pad %} → {{ pad.display_slug|dewikify }}{% endif %}</title>
    
</head>
<body class="pad-{{ pad.display_name|slugify }} {{ mode }}-mode {% if user.is_authenticated and author %}logged-in{% else %}logged-out{% endif %} {% block bodyclasses %}{% endblock %}">
    <nav id="nav-left">
        <h1><a id="logo" data-article="{% block data_article %}{% endblock%}" href="/">{{ site_name }}</a></h1>
        <a class="button screen-only" href="/r/About.md">About</a>
        
        
        <div id="sort-by">Sort by:
            <a class="{% if sort == 'date' %}active{% endif %} button screen-only" href="/?sort=date">Date</a>
            <a class="{% if sort == 'tags' %}active{% endif %} button screen-only" href="/?sort=tags">Tag</a>
            <a class="{% if sort == 'authors' %}active{% endif %} button screen-only" href="/?sort=authors">Author</a>
        </div>
        {% block extra_nav %}{% endblock %}

        {% if user.is_authenticated and author %}
        <div id="staff-menu" class="private">
            <span class="screen-only">{{ author.full_name_with_prefix }}</span>
            <a class="button screen-only" href="{% url 'logout' %}{% if pad %}?next={% url 'pad-read' 'r' pad.display_slug %}{% endif %}">Log out</a>
            <a class="button screen-only" href="{% url 'pad-create' %}">Create</a>
            <a class="button screen-only" href="{% url 'all' %}">List</a>
            <a class="button screen-only" href="{% url 'publish' %}">Re-index</a>
            <a class="button screen-only" href="/w/screen.css">screen.css</a>
            <a class="button screen-only" href="/w/laser.css">laser.css</a>
            <a class="button screen-only" href="/w/offset.css">offset.css</a>
            <a class="button screen-only" href="/w/documentation.md">documentation</a>
            {% else %}
            <a class="button" href="{% url 'login' %}">Log in</a>
        </div>
        {% endif %}
    </nav>
    <nav id="nav-right">
        {% if pad %}
            <a class="button screen-only read-button" href="{% url 'pad-read' 'r' pad.display_slug %}">Read</a>
            <a class="button screen-only slide-button" href="{% url 'pad-read' 's' pad.display_slug %}">Slide</a>
            <a class="button screen-only" href="{% url 'pad-read' 'p' pad.display_slug %}">Print</a>
            {% if user.is_authenticated %}
                <a class="button screen-only write-button" href="{% url 'pad-write' pad.display_slug %}">Write</a>
            {% else %}
                <a class="button screen-only write-button" href="{% url 'login' %}">Write</a>
            {% endif %}
        {% endif %}
    </nav>
    <div class="wrap">
        <div class="left-side screen-only">
            {% block title_left %}{% endblock %}
        </div>

        <div class="middle">
            {% block title %}{% endblock %}
        </div>

        <div class="right-side screen-only">
            {% block title_right %}{% endblock %}
        </div>
    </div>

    <div class="wrap" style="height: 85%;">
        <div class="left-side screen-only">
        </div>
        <div class="middle">
            <div id="content" class="{% block contentclasses %}{% endblock %}">
                {% block content %}{% endblock %}
            </div>
        </div>
        <div class="right-side screen-only">
            {% block rightside %}{% endblock %}
        </div>
    </div>
    {% block extraui %}{% endblock %}


    

    <script src="{{ STATIC_URL }}js/relearn.js" type="text/javascript" charset="utf-8"> </script>
    <script src="{{ STATIC_URL }}js/comments/comments.js" type="text/javascript" charset="utf-8"> </script>

    {% if user.is_authenticated and author %}
        <script>
            $(function() {
                $("#content").revealComments();
            });
        </script>
    {% endif %}


{% block scripts %}{% endblock %}
</body>
</html>

relearn/templates/commits.html
<div class="commits">
{% extends "base.html" %}

{% block contentclasses %}commits-col{% endblock %}

{% block content %}
            {% for commit in all_commits %}
            <h3>{{ commit.repo_name }}</h3>
            <p class='commit-message'>{{ commit.message|urlize|linebreaksbr }}</p>
            <p>By <span class='commit-author'>{{ commit.author }}</span> on <span class='commit-date'>{{ commit.commit_time }}</span></p>

            {% endfor %}
{% endblock %}
</div>

relearn/templates/form.html
<!DOCTYPE HTML>
<html>
<head>
    <meta http-equiv="content-type" content="text/html; charset=utf-8">
    <title>Relearn</title>
    <link rel="stylesheet/less" href="{{ STATIC_URL }}less/relearn.less" type="text/css" media="screen" charset="utf-8">
    <script src="{{ STATIC_URL }}js/less-1.4.1.min.js" type="text/javascript" charset="utf-8"></script>
    <style type="text/css" media="screen">
        body {
            background: none;
        }
        
    </style>
</head>
<body>
<form id="email-form" action="{% url 'relearn-issue-send' %}" method="post" accept-charset="utf-8">
    {% csrf_token %}
    <div>
        <input style="width: 45%; display: inline; margin-right: 10px;" id="id_name" maxlength="50" name="name" type="text" value="{{ user.get_full_name }}"/>
        <!--<input style="width: 45%; display: inline;" id="id_email" name="email" type="text" value="{{ user.email }}" />-->
    </div>
    <div style="margin-top: 3px;">
        <label style="width: 25%; display: inline;" for="id_subject">Subject</label> 
        <input style="width: 73%; display: inline;" id="id_subject" maxlength="100" name="subject" type="text" />
    </div>
    <div style="margin-top: 3px;">
        <textarea style="width: 96%; height: 6em;" id="id_message" name="message"></textarea>
    </div>
    <p><input type="submit" value="Send"></p>
</form>
</body>
</html>

relearn/templates/home.html
{% extends "pad-base.html" %}
{% load wikify relearn_tags %}

{% block extra_styles %}
    <link rel="stylesheet" href="/css/" type="text/css" media="screen">
    <link rel="stylesheet/less" href="/css-print/" type="text/css" media="print">
{% endblock %}

{% block head_meta %}

    <meta property="og:image" content="http://f-u-t-u-r-e.org/media/images/eyes/{{ EYES }}"/>
    <meta name="description" content="<o> future <o>  is an editorial project conceived to approach horizontally the activities of writing, publishing and designing texts dedicated to art, media and design among other subjects. <o> future <o>  publishes texts online as much as in books."/>

{% endblock %}

{% block bodyclasses %}pad-00md{% endblock %}

{% block extra_nav %}
    <div id="sort-by">Sort by:
        <a class="{% if not sort %}active{% endif %} button screen-only" href="/">Date</a>
        <a class="{% if sort == 'author' %}active{% endif %} button screen-only" href="?sort=author">Author</a>
        <a class="{% if sort == 'book' %}active{% endif %} button screen-only" href="?sort=book">Book</a>
    </div>
{% endblock %}


{% block title %}
    <header>
    <style>
    body {
        background-image: url("/media/images/eyes/{{ EYES }}");
    }
    </style>
        

    <h1>
        <span property="dc:title">Index</span>
    </h1>
    </header>
{% endblock %}

{% block content %}
    <ul>
    {% for article in articles %}
        {% if forloop.counter.last %}
            <li>
        {% endif %}
        {% ifchanged article.id %}
        </li>
        <li {% if article.type %}data-type="{{ article.type }}"{% endif %}>
                <span class="authors">{{ article.authors|natural_join:'&'|markdown_filter }}</span> 
        {% endifchanged %}

        <a href="{{ article.href }}" lang="{{ article.language }}">{{ article.title|markdown_filter }}</a>

        {% if forloop.counter.last %}
            </li>
        {% endif %}
    {% endfor %}
    </ul>
    {{ pub|safe }}
{% endblock %}

{% block rightside %}
{% endblock %}

{% block extraui %}
{% if not user.is_authenticated %}
<div class="popup-wrapper hidden">
    <div class="popup">
      <form method="post" action="{% url 'django.contrib.auth.views.login' %}">
        {% csrf_token %}
        <label for="id_username">Username</label>
        <input id="id_username" maxlength="254" name="username" type="text" />
        <label for="id_password">Password</label>
        <input id="id_password" name="password" type="password" />
    
        <input class="submit" type="submit" value="Login" />
        <input type="hidden" name="next" value="{% if next %}{{ next }}{% else %}{% url 'home' %}{% endif %}" />
      </form>
    </div>
</div>
{% endif %}
{% endblock %}

relearn/templates/issue.html
<!DOCTYPE HTML>
<html>
<head>
    <meta http-equiv="content-type" content="text/html; charset=utf-8">
    <title>Relearn</title>
    <link rel="stylesheet/less" href="{{ STATIC_URL }}less/relearn.less" type="text/css" media="screen" charset="utf-8">
    <script src="{{ STATIC_URL }}js/less-1.4.1.min.js" type="text/javascript" charset="utf-8"></script>
    <style type="text/css" media="screen">
        body {
            background: none;
        }
        
    </style>
</head>
<body>
    <p>Your issue has been sent. You will receive it through the mailing-list and out of the printer in the common room.</<p>
    <p><a href="/send-issue/">Point out another issue.</a></p>
    
</body>
</html>

relearn/templates/login.html
{% extends "base.html" %}
{% load i18n %}

{% block title %}
    <h1>{% trans "Login" %}</h1>
{% endblock %}

{% block content %}
  {% if not user.is_authenticated %}
      {% if form.errors %}
      <p class="error">{% trans "Your username and password didn't match. Please try again." %}</p>
      {% endif %}
    
      <form method="post" action="{% url 'django.contrib.auth.views.login' %}">
        {% csrf_token %}
            {{ form.username.label_tag }}
            {{ form.username }}
            {{ form.password.label_tag }}
            {{ form.password }}
    
        <input class="submit" type="submit" value="{% trans "Login" %}" />
        <input type="hidden" name="next" value="{% if next %}{{ next }}{% else %}{% url 'starter' %}{% endif %}" />
      </form>
    {% else %}
    <p>You are already logged in—welcome!</p>
    {% endif %}
{% endblock %}

relearn/templates/logout.html
{% extends "base.html" %}
{% load i18n %}

{% block title %}
<h1>{% trans "Logout" %}</h1>
{% endblock %}

{% block content %}
<h2>{% trans "You have been logged out." %} <a href="{% url 'login' %}">{% trans "Log back in." %}</a></h2>

{% endblock %}

relearn/templates/pad-create.html
{% extends "base.html" %}
{% load url from future %}
{% load i18n %}


{% block title %}
      <h1>{{ title }}</h1>
{% endblock %}

{% block content %}
  <form action="{% url 'pad-create' %}" method="post">
        {% csrf_token %}
        Pad name
        {{ form.name }}
        {{ form.group }}
        <input class="submit" type="submit" value="{%trans "Create" %}" />
  </form>
  <legend></legend>
{% endblock %}

relearn/templates/pad-slide.html
{% extends "base.html" %}
{% load wikify relearn_tags %}

{% block extra_styles %}
    <link rel='stylesheet' href='/static/js/slidy.css' type='text/css' media='all' />
    <link rel='stylesheet' href='/css-slide/' type='text/css' media='all' />
    <link rel="stylesheet/less" href="{% url 'css' %}" type="text/css" media="screen">
    <link rel="stylesheet/less" href="/css-slide/" type="text/css" media="all">
{% endblock %}


{% block head_meta %}
    <meta property="og:type" content="article"/>
{% if meta %}

    {% if meta.authors %}
        {% for author in meta.authors %}
            <meta property="dc:creator" content="{{ author }}" />
        {% endfor %}
    {% endif %}
    {% if meta.language %}{% for language in meta.language %}<meta property="dc:language" content="{{ language|lower }}" />{% endfor %}{% endif %}

    <meta property="dc:identifier" content="{{ meta.id.0 }}" />
    {% if meta.type %}<meta property="dc:type" content="{{ meta.type.0 }}" />{% endif %}
{% endif %}
{% endblock %}


{% block data_article %}{{ meta.authors|natural_join:'&'|markdown_filter|no_p }}, {{ meta.title.0 }}{% endblock %}

{% block bodyclasses%}{% if meta.host %}{{ meta.host.0|lower }}{% endif %} {% if meta.type %}{{ meta.type.0|lower }}{% endif %}{% endblock %}
{% block contentclasses%}{% if meta.host %}{{ meta.host.0|lower }}{% endif %} {% if meta.type %}{{ meta.type.0|lower }}{% endif %}{% endblock %}


{% block content %}
    {{ text|safe }}
{% endblock %}

{% block scripts %}
    <script src="/static/js/slidy.js"> </script>

    <script>
    // REMOVE THIS WHOLE SCRIPT TAG FOR LOCAL VERSION //
    $(document).ready(function(){
        // DIV WRAPPER AROUND EACH H2
        $("#content h2").each(function(){
            h2 = $(this).attr('id');
            $(this).nextUntil('h2').andSelf().wrapAll('<div class="slide ' + h2 + '"></div>');
        });
    });
    </script>
{% endblock %}

relearn/templates/publish.html
{% extends "base.html" %}

{% block extra_styles %}
    <link rel="stylesheet/less" href="/css/" type="text/css" media="screen">
    <link rel="stylesheet" href="{{ STATIC_URL }}css/progress.css" type="text/css" media="all">
{% endblock %}

{% block content %}
{% if published %}
<p style="background-color: white">Succesfully re-indexed/published.</p>
<p style="background-color: white">{{ message|title }}.</p>
<p>View <a href="{% url 'starter' %}">home page</a></p>
{% else %}
<div id="loading">
    <div class="meter red">
        <span style="width: 25%"></span>
    </div>
    <p>Publishing, please don’t stop or refresh this page:</p>
    <p>This might take up to a minute.</p>
</div>
<form action="" method="post">
    {% csrf_token %}
    <input style="" type="submit" class="submit" value="Re-index"/>
</form>
<script>
    $("input[type=submit]").click(function() {
        $(this).hide();
        $("#loading").show();
    });
</script>

{% endif %}
{% endblock %}

relearn/templates/tracker.html
{% extends "base.html" %}

{% block content %}
<h1>Tracker</h1>
<form action="tracker_submit" method="get" accept-charset="utf-8">
    <p><label>ID</label><input name="id" type="text" value="" /></p>
    <p><label>Date/Time</label><input name="datetime" type="text" value="" /></p>
    <p><label>Name</label><input name="name" type="text" value="" /></p>
    <p><label>Text</label><textarea name="text" cols="80" rows="10" value=""></textarea></p>
    <p><input type="submit" value="Continue &rarr;" /></p>
</form>
{% endblock %}